
#net.minecraft.scalar.mineall.mod_MineAllSMP
[configuration]
	#Boolean: true
	DestroyUnder = true
	#Boolean: true
	StartMode = true
	#String: "iron_pickaxe, wooden_pickaxe, stone_pickaxe, diamond_pickaxe, golden_pickaxe"
	itemIds = "iron_pickaxe, wooden_pickaxe, stone_pickaxe, diamond_pickaxe, golden_pickaxe"
	#Boolean: false
	DropGather = false
	#String: "gold_ore, iron_ore, coal_ore, lapis_ore, obsidian, diamond_ore, redstone_ore, glowstone, emerald_ore, nether_quartz_ore, granite, polished_granite, diorite, polished_diorite, andesite, polished_andesite"
	blockIds = "gold_ore, iron_ore, coal_ore, lapis_ore, obsidian, diamond_ore, redstone_ore, glowstone, emerald_ore, nether_quartz_ore, granite"
	#Integer: 0
	#0:not decrease durability 1,2:decrease durability(1=until whole blocks 2=until break an item)
	Durability = 0
	#String: "mod_mineall"
	channelName = "mod_mineall"
	#Boolean: false
	AutoCollect = false
	#String: "KEY_M"
	Key = "KEY_M"
	#Integer: 0
	Limiter = 0

